create table t_classmate
(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	gender TINYINT NOT NULL DEFAULT 0,
	password VARCHAR(32) NOT NULL,
	phone VARCHAR(13),
	work_city VARCHAR(32),
	work_addr VARCHAR(255),
	home_town VARCHAR(32),
	home_addr VARCHAR(255),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);